name: C/C++ CI

on:
  push:
    branches:
    - master
    - github-actions-changes
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Run Action
      uses: addnab/docker-run-action@v1
      with:
        # Image
        image:  sriharshasingam/ubuntu-i386-elf-gcc-cross-compiler:latest
        # Options
        options: -ti -v $PWD:/src --name ubuntu-cross-compiler 
        # Run command in container
        run: cd HarshOS && make os.iso && make kernel.elf
        # Use a specific shell
        shell: bash
    - uses: actions/checkout@v2
    - name: configure_env
      run: ./configure_cross_compiler.sh
    - name: make github-actions-os-iso
      run: sudo make github-actions-os-iso
    - uses: actions/upload-artifact@v2
      with:
        name: OS Boot ISO Image
        path: build_os/os.iso
    - uses: actions/upload-artifact@v2
      with:  
        name: Kernel Binary
        path: build_os/kernel.bin
    - uses: actions/upload-artifact@v2
      with:  
        name: Kernel ELF Executable with Debug Symbols
        path: build_os/kernel.elf
    - uses: actions/upload-artifact@v2
      with:  
        name: Main Bootloader Image
        path: build_os/boot_sector_main.bin
    - uses: actions/upload-artifact@v2
      with:
        name: Second Bootloader Image
        path: build_os/second_stage_bootsector.bin
    - uses: actions/upload-artifact@v2
      with:
        name: Initial Kernel Filesystem Image
        path: build_os/harshfs_kernel_initial_image.bin
